export const onboardingSections = [
    {
        sectionId: "employeeDetails",
        title: "Employee Details",
        icon: "MdBusinessCenter",
        fields: [
            {
                id: "legalEntity",
                label: "Legal Entity",
                type: "select",
                required: true,
                grid: { sm: 12, md: 6, lg: 4 },
                options: ["SoGo Corporation", "SoGo Technologies", "SoGo Services", "Other"],
            },
            {
                id: "businessUnit",
                label: "Business Unit",
                type: "select",
                required: true,
                grid: { sm: 12, md: 6, lg: 4 },
                options: ["Human Resources", "Finance", "Sales & Marketing", "Operations", "Other"],
            },
            {
                id: "employmentType",
                label: "Employment Type",
                type: "select",
                required: true,
                grid: { sm: 12, md: 6, lg: 4 },
                options: ["Full-Time", "Part-Time", "Contract", "Intern"],
            },
            {
                id: "hireDate",
                label: "Hire Date",
                type: "date",
                required: true,
                grid: { sm: 12, md: 6, lg: 4 },
            },
            {
                id: "employeeCode",
                label: "Employee Code",
                type: "text",
                readonly: true,
                grid: { sm: 12, md: 6, lg: 4 },
            },
        ],
    },
    {
        sectionId: "personalDetails",
        title: "Personal Details",
        icon: "MdPerson",
        fields: [
            { id: "firstName", label: "First Name", type: "text", required: true, grid: { sm: 12, md: 6, lg: 4 } },
            { id: "middleName", label: "Middle Name", type: "text", grid: { sm: 12, md: 6, lg: 4 } },
            { id: "lastName", label: "Last Name", type: "text", required: true, grid: { sm: 12, md: 6, lg: 4 } },
            { id: "displayName", label: "Display Name", type: "text", readonly: true, grid: { sm: 12, md: 6, lg: 4 } },
            { id: "email", label: "Email Address", type: "email", required: true, grid: { sm: 12, md: 6, lg: 4 } },
            { id: "phone", label: "Phone Number", type: "tel", required: true, grid: { sm: 12, md: 6, lg: 4 } },
            { id: "alternatePhone", label: "Alternate Phone", type: "tel", grid: { sm: 12, md: 6, lg: 4 } },
            { id: "dob", label: "Date of Birth", type: "date", required: true, grid: { sm: 12, md: 6, lg: 4 } },
            {
                id: "maritalStatus",
                label: "Marital Status",
                type: "select",
                grid: { sm: 12, md: 6, lg: 4 },
                options: ["Single", "Married", "Divorced", "Widowed", "Prefer Not to Say"],
            },
            // structured current address
            {
                id: "currentAddress",
                label: "Current Address",
                type: "addressGroup",
                required: true,
                grid: { sm: 12 },
                fields: [
                    { id: "line1", label: "Address Line 1", type: "text", required: true, grid: { sm: 12, md: 6, lg: 6 } },
                    { id: "city", label: "City", type: "text", required: true, grid: { sm: 12, md: 6, lg: 3 } },
                    { id: "state", label: "State", type: "text", required: true, grid: { sm: 12, md: 6, lg: 3 } },
                    { id: "postalCode", label: "Postal Code", type: "text", required: true, grid: { sm: 12, md: 6, lg: 3 } },
                ],
            },
            { id: "sameAddress", label: "Same as Current Address", type: "checkbox", grid: { sm: 12 } },
            {
                id: "permanentAddress",
                label: "Permanent Address",
                type: "addressGroup",
                required: true,
                grid: { sm: 12 },
                fields: [
                    { id: "line1", label: "Address Line 1", type: "text", required: true, grid: { sm: 12, md: 6, lg: 6 } },
                    { id: "city", label: "City", type: "text", required: true, grid: { sm: 12, md: 6, lg: 3 } },
                    { id: "state", label: "State", type: "text", required: true, grid: { sm: 12, md: 6, lg: 3 } },
                    { id: "postalCode", label: "Postal Code", type: "text", required: true, grid: { sm: 12, md: 6, lg: 3 } },
                ],
            },
            { id: "emergencyName", label: "Emergency Contact Name", type: "text", required: true, grid: { sm: 12, md: 6 } },
            { id: "emergencyPhone", label: "Emergency Contact Phone", type: "tel", required: true, grid: { sm: 12, md: 6} },
        ],
    },
];
